Added CSS to the theme
UCF/Online-Child-Theme pull request #137
Opened 2021-11-09 14:42 UTC by rjucf

**Description**

Incorporated CSS that was being included via UCF page assets

**Motivation and Context**

UCF Online request and performance improvements.

**How Has This Been Tested?**

Tested in DEV

**Types of changes**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Checklist:**

- [ ] My code follows the code style of this project.
- [ ] My change requires an update to the documentation.
- [ ] I have updated the documentation accordingly.

2021-11-09 14:55 UTC, jmbarne3 approved these changes

2021-11-09 15:06 UTC, cadie approved these changes

2021-11-09 15:16 UTC, cjg89 requested changes

2021-11-09 15:16 UTC, cjg89 commented on src/scss/_variables.scss
> +$ucf-gold: #fc0;
`$ucf-gold` is already defined in Athena and can be removed (Athena variables don't need to be re-defined in this file unless they need to be overridden or referenced elsewhere in this file)

2021-11-09 15:16 UTC, cjg89 commented on src/scss/templates/_single-landing.scss
> +  #ucfhb {
Landing pages should already have the UCF Header omitted from them: https://github.com/UCF/Online-Child-Theme/blob/master/includes/meta.php#L16-L20

If that snippet isn't working, we should address it instead of using CSS to hide the header.

2021-11-09 15:16 UTC, cjg89 commented on src/scss/templates/_single-degree.scss
> +        font-size: 3rem;
Awkward tabbing here

2021-11-09 15:16 UTC, cjg89 commented on src/scss/templates/_single-degree.scss
> +  @media screen and (min-width:992px) {
Athena breakpoint mixins are preferred over media queries (`@include media-breakpoint-up(...)`)

2021-11-09 15:16 UTC, cjg89 commented on src/scss/templates/_single-degree.scss
> +  @media screen and (max-width:991px) {
Athena breakpoint mixins are preferred over media queries

2021-11-09 15:16 UTC, cjg89 commented on src/scss/templates/_single-degree.scss
> +    background-image: url(https://www.ucf.edu/online/files/2019/12/arrow-down-1.png);
Asset URLs like this shouldn't be hard-coded into our stylesheets; relative asset paths are preferred.

Alternatively, this kind of asset might be better suited as an inline SVG, where we don't have to deal with pixelation issues when resized or stretched, and colors can be defined on the fly with Sass variables (example: https://github.com/UCF/Athena-Framework/blob/master/src/scss/_variables.scss#L818)

2021-11-10 19:54 UTC, cjg89 commented on src/scss/templates/_single-landing.scss
> +  #ucfhb {
Marking as resolved since this snippet helps to hide the inline UCF Header placeholder div inserted on all pages by the UCF WP Theme.  Will open a separate issue in that theme to address being able to toggle that placeholder div somehow.

2021-11-10 19:54 UTC, cjg89 approved these changes

2021-11-10 19:56 UTC, rjucf commented on src/scss/templates/_single-landing.scss
> +  #ucfhb {
The UCF-WordPress-Theme contains the div with a black background and CSS is the best way to hide the black bar at this time. The wp_deregister_script( 'ucf-header' ) code is working properly.

2021-11-10 19:56 UTC, merged