Acf template
UCF/Online-Child-Theme pull request #149
Opened 2022-06-22 19:28 UTC by rjucf

**Description**

Created a new template for the degree post type called ACF Template. The template will be used going forward to transition the online degrees from the default template which is mostly custom HTML for each template. Most of the code in this PR has been copied from the Main Site Theme will some small changes specific to the Online Theme.

**Motivation and Context**

Client request.

**How Has This Been Tested?**

Tested in DEV

**Types of changes**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Checklist:**

- [ ] My code follows the code style of this project.
- [ ] My change requires an update to the documentation.
- [ ] I have updated the documentation accordingly.

2022-06-22 19:58 UTC, jmbarne3 requested changes

2022-06-27 16:00 UTC, jmbarne3 approved these changes

2022-06-27 16:00 UTC, jmbarne3 commented on dev/acf-export.json
> +]
Newline needs to be added to the end of the file.

2022-06-27 16:00 UTC, jmbarne3 commented on single-degree-acf.php
> +<?php get_footer(); ?>
Add new line.

2022-06-28 13:04 UTC, cadie approved these changes

2022-06-28 13:36 UTC, merged